image: tano297/bonnet:cuda9-cudnn7

stages:
  - build

build:
  stage: build
  before_script:
  - export TERM=xterm
  - export SHELL=/bin/bash
  - export PATH=/usr/local/cuda-9.0/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
  - export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:$LD_LIBRARY_PATH

  - apt-get install -y python-pip python-empy
  - pip install -U pip catkin-tools trollius

  script:
  - source /opt/ros/kinetic/setup.bash
  - cd deploy_cpp/standalone # build standalone apps
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j
  - cd ../../../
  - mkdir -p ~/catkin_ws/src/bonnet/ # build ros nodes
  - cp -r ./* ~/catkin_ws/src/bonnet/
  - cd ~/catkin_ws
  - catkin init
  - catkin build

  tags:
  - docker
