# train cfg file
max_epochs: 1000
lr: 0.001           # learning rate
decay1: 0.9         # decay for first order momentum
decay2: 0.99        # decay for second order momentum
lr_decay: 75        # decay learning rate every x epochs
lr_rate: 2          # decay in halves
acc_report_epochs: 10 # every x steps, report accuracy
batch_size: 20      # batch size
gpus: 2             # number of gpus to use
save_imgs: True     # False doesn't save anything, True saves some 
                    # sample images (one per batch of the last calculated batch)
                    # in log folder
summary: False      # verbose summary
summary_freq: 50    # steps for summary                    